version: '3.4'

services:
  dockerandmongosamplewebapp:
    image: dockerandmongosamplewebapp
    build:
      context: .
      dockerfile: DockerAndMongoSampleWebApp/Dockerfile
    ports:
      - "20000:80"    
    depends_on:
      - "mongodockersample"

  mongodockersample:
    image: mongo
    restart: always      
    ports:
      - "27099:27017"
